Repository AspectOfJerry/JerryBot, pull requests merged in 2022-12, with the labels that each got.

#83 Master
  commands/tests/AG/AGTest.js
Labels: wip, priority

#85 Add new command
  commands/tests/AG/poll.js
Labels: wip, urgent

#88 Fixed typo
  commands/tests/AG/poll.js
Labels: bug, wip, urgent

#90 Fixed reaction not trigering
  commands/tests/AG/random.js
Labels: enhancement, help wanted, wip, priority
